name: Skyblock
main: xyz.oribuin.skyblock.Skyblock
version: @version@
author: Oribuin
api-version: "1.16"
description: All skyblock plugins suck so i made my own kekW
website: https://oribuin.xyz/
depend:
  - WorldEdit
softdepend:
  - PlaceholderAPI
loadbefore:
  - Multiverse-Core
commands:
  island:
    description: Main Island Command
    usage: /island
    aliases:
      - is