name: Skyblock
main: xyz.oribuin.skyblock.Skyblock
version: @version@
author: Oribuin
api-version: "1.13"
description: Skyblock plugin designed and created by Oribuin
website: https://oribuin.xyz/
softdepend:
  - PlaceholderAPI
loadbefore:
  - Multiverse-Core
commands:
  island:
    description: Main Island Command
    usage: /island
    aliases:
      - is